import Head from 'next/head'
export const metadata = {
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      noimageindex: true
    }
  },
  title: "Create Next App",
  description: "Generated by create next app",
  keywords: ['Allan', 'Allan Pires', 'Desenvolvedor frontend'],
  authors: [{name: "Allan Pires"}],
  icons: []
}

export default function Home() {
  return (
    <>
      <div id='desconto' className="flex items-center justify-center w-full py-1 bg-blue-500">
        <span className="text-white uppercase font-[500]">Compre com 30% de desconto até 25/10</span>
      </div>

      <main className="flex w-full bg-[url(/images/background.jpeg)] relative bg-cover">
        <div className='absolute inset-0 bg-black opacity-50'></div>

        <div className='flex pt-8 pb-12 px-[24px] flex-col items-center justify-center z-5 relative'>
          <img src='/images/apostila.webp' alt="" width={235} height={235} />

          <h1 className="text-[22px] text-center font-[600] mt-1">Garanta sua aprovação no INSS para o cargo de Técnico do Seguro Social</h1>

          <p className="text-[18px] font-[400] text-center mt-3 mb-6">Prepare-se para o concurso do INSS através do melhor material de estudos disponível na internet! Agora você pode estudar de maneira eficiente e direcionada para as provas, com foco na sua aprovação!</p>

          <a href="#" className='bg-blue-500 py-3 px-12 rounded-[7px] font-semibold uppercase text-[16px]'>Garantir com 30% OFF</a>
        </div>
      </main>
    </>
  )
}
